### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by whitegolum** [NotHunter101/ExtraRolesAmongUs#1]
If u don't mind me asking , what's the thing you added into your code that made you able to load more than one mod at a time ? how did u deal with the overlap of mods ? that someone can get more than one extra role in the same game ?

**Comment by Snowad14** [comment]
it is possible I did not see its code but personally I had taken all the players and each time I added a role I deleted it from the list which allows to play with several roles

**Comment by NotHunter101** [comment]
Snowad14 is correct; all the roles are one mod. I created a list containing every crewmate in a RpcSetInfected postfix patch, and every time I added a role, I just removed that player from the list of crewmates. You can look at the RpcSetInfected patch in MainHooks.cs for more information.

**Comment by whitegolum** [comment]
Can i text u on private NotHunter101 got a work for u to do

**Comment by NotHunter101** [comment]
Sure? My discord is Hunter101#1337
