### ISSUE TITLE
Issue, how do i make it work?

### ISSUE THREAD

**Issue by mrPhoenix-tech** [NotHunter101/ExtraRolesAmongUs#118]
![image](https://user-images.githubusercontent.com/74743378/133906595-1c700893-7255-4dc6-a343-6a3872481bfe.png)

**Comment by The1Unkn0wn** [comment]
I had the same issue

**Comment by The1Unkn0wn** [comment]
Did you ever figure it out?

**Comment by NotHunter101** [comment]
This mod hasn't been maintened or updated in months, and since the game has updated it no longer boots at all. I'd suggest you try to find another role mod that works on the latest version.
