### ISSUE TITLE
Medic Shield Imposter

### ISSUE THREAD

**Issue by UnknownHobbyist** [NotHunter101/ExtraRolesAmongUs#14]
I dont know if it is intended but if the medic shields the imposter and the sherif trys to kill the imposter he performs suicide instead.

**Comment by benniii1337** [comment]
Sounds intented for me. It's kinda the medics fault if he shields an imposter, because he decided that he is a crewmate. It extends the mindgames. Could be an option do disable that behaviour, though.

**Comment by NotHunter101** [comment]
This is intentional behavior. See above.
