### ISSUE TITLE
Provide releases as ZIP-files

### ISSUE THREAD

**Issue by moritzruth** [NotHunter101/ExtraRolesAmongUs#15]
RAR-files cannot be extracted with the Windows Explorer. This makes the installation unnecessarily difficult for most users.

I suggest providing releases as ZIP-files in addition to RAR-files so that users who are comfortable with RAR-files can benefit from the smaller file size and everyone else has fewer problems.

**Comment by NotHunter101** [comment]
I agree, I'm not sure why it hasn't crossed my mind to add a .zip file in new releases instead, but I will do this for new ones in the future. It is already done for the current build.

**Comment by moritzruth** [comment]
Thank you!
