### ISSUE TITLE
Can't do download task as an engineer

### ISSUE THREAD

**Issue by AlexisL61** [NotHunter101/ExtraRolesAmongUs#16]
Hello,
When you are an engineer and you have a download task in electrical you can't do it because you are on a vent and you will use the vent instead of doing the task.
I hope it will help for future update!

**Comment by benniii1337** [comment]
Instead of using the keyshortcut, you could click on the download, can't you?

**Comment by NotHunter101** [comment]
Yes, this is a known quirk that doesn't need much explaining. The above comment is a correct workaround; simply click the download panel to open it. (This will most likely be fixed, eventually)
