### ISSUE TITLE
Vote Skip Bug Role Mod 1.2.5

### ISSUE THREAD

**Issue by jackboi03** [NotHunter101/ExtraRolesAmongUs#21]
Hey,
We encountered a bug when we skipped vote, that the game froze in the "vote skipped screen.
In the console there also was an error, but I do not have it right now.
When we voted someone out, it worked perfect.
We also ensured, that everyone has the 1.2.5 Version of the mod.
I hope this helps fixing this issue.
Have a great day!

**Comment by NotHunter101** [comment]
I will post a hotfix in a few minutes that fixes this issue. I will send a new comment when it is done, and you can all download a new verison.

**Comment by NotHunter101** [comment]
I posted a new patch that should fix this issue. Download it in the releases tab.
