### ISSUE TITLE
I can't see joker spawn chance on menu

### ISSUE THREAD

**Issue by mannaggacardarell** [NotHunter101/ExtraRolesAmongUs#23]
I can't see joker spawn chance on menu. I can't scroll down more
https://prnt.sc/zdyf9h

**Comment by NotHunter101** [comment]
This is a known bug. The current workaround is to just click where the arrows would be if you could see them (under the actual laptop menu)

**Comment by mannaggacardarell** [comment]
Ah ok is not a problem for me becasue yes, i press. Btw thanks for all your job!
