### ISSUE TITLE
Crewlink issue

### ISSUE THREAD

**Issue by FreshImmuc** [NotHunter101/ExtraRolesAmongUs#24]
Crewlink doesnt work

**Comment by itsoskurr** [comment]
Then it's up to you. I often played with people who used Crewlink and the mod and we had no problems.

**Comment by itsoskurr** [comment]
> Crewlink doesnt work

Try to reinstall Crewlink ore use Better-Crewlink

**Comment by NotHunter101** [comment]
I've played the mod with Crewlink a lot, and I've seen others on Twitch and Discord play with Crewlink, too. Unless you provide me with more information in a new issue, I cannot help you.
