### ISSUE TITLE
AntiCheat of Impostor server bans Engineers who try to went

### ISSUE THREAD

**Issue by Phoenix616** [NotHunter101/ExtraRolesAmongUs#25]
When trying to went as an Engineer the Impostor anti cheat bans them from the server because of hacking:

`Client 22 disconnecting, reason: Client sent EnterVent as crewmate`

Not sure if this would be solvable by an Impostor plugin or only if disabling the Impostor anti cheat (which is currently not an option :S)

**Comment by NotHunter101** [comment]
Duplicate of https://github.com/NotHunter101/ExtraRolesAmongUs/issues/6
