### ISSUE TITLE
Others can't see Engineer Vent

### ISSUE THREAD

**Issue by pedroumbelino** [NotHunter101/ExtraRolesAmongUs#26]
Do other players watch the Engineer Vent? Cause to me the Engineer itself can see the Vent Animation but others can't. The player remains still on top of the Vent until the Engineers leaves the vent AND changes position

**Comment by NotHunter101** [comment]
Make sure everybody in your lobby has the same version of the mod because I have never seen this issue in normal play before. If it still doesn't work, have everyone in your game delete the entire Among Us folder, re-install the game, and then re-install the mod.

**Comment by NotHunter101** [comment]
Resolved by pedroumbelino in another thread.
