### ISSUE TITLE
Engineer can Sabotage while dead

### ISSUE THREAD

**Issue by JoeRoll1** [NotHunter101/ExtraRolesAmongUs#27]
Hello there! Been having a lot of fun with this. My friends and I realized that Engineers can call a sabotage whenever they are dead despite the greyed out buttons.

**Comment by NotHunter101** [comment]
Pretty sure this was fixed in a recent patch, so try updating to the latest version.

**Comment by NotHunter101** [comment]
I can no longer reproduce this in the latest version, so I assume this bug has been fixed. Reopen this if you can make it happen consitently.
