### ISSUE TITLE
Proposal: Option so Joker can see impostors

### ISSUE THREAD

**Issue by webfussel** [NotHunter101/ExtraRolesAmongUs#28]
We had a lot of fun playing this Mod yesterday but found a flaw with the Joker.

The goal of the Joker is to get dropped from the ship to win. It's an interesting role, because you have to pretend to be an impostor who pretends to be a crewmate.

In some rounds we had the Joker get killed very first from an imposter.
The Joker could not do anything for the rest of the game, because they didn't have any tasks either. It got very boring because of that, so we turned Joker off for some time.

My proposal would be an option for the Joker to see who the impostors are, so they don't get killed right away and do nothing for the rest of the game.

**Comment by NotHunter101** [comment]
This isn't an issue. Join the Discord if you wish to post feature suggestions.
