### ISSUE TITLE
Unable to access task as engineer

### ISSUE THREAD

**Issue by WireAngel** [NotHunter101/ExtraRolesAmongUs#30]
On the map polus, I was not able to access the cable task on top of the vent as an engineer. Since you are able to use the vent AND the task, all options I tried (LMB, space, E) caused me to use the vent, preventing me from finishing the task while alive.

**Comment by NotHunter101** [comment]
Duplicate of https://github.com/NotHunter101/ExtraRolesAmongUs/issues/16. Click on the task with your mouse cursor.
