### ISSUE TITLE
3 questions

### ISSUE THREAD

**Issue by Pixelplayz2215YT** [NotHunter101/ExtraRolesAmongUs#31]
1. Does this work with latest version

2. How would I go about to reverting to original Among Us

3. Can I use other Role mods with this?

**Comment by NotHunter101** [comment]
1. Yes, it works with 12.9.
2. Renaming the BepInEx folder to anything else.
3. No.

In the future, refrain from posting questions in the issues tab, and join the Discord instead.

**Comment by Pixelplayz2215YT** [comment]
Thanks :)

**Comment by Pixelplayz2215YT** [comment]
@NotHunter101 Where can I find game codes that are playing with this mod?
