### ISSUE TITLE
[BUG] Officer kills 2nd imposter, game doesn't end

### ISSUE THREAD

**Issue by dketterer** [NotHunter101/ExtraRolesAmongUs#38]
We encountered a situation where the **first imposter was voted out during a meeting** and **the second one shot by the officer, but the game didn't end**. By chance someone different pinged out right after that and the game ended then with the right state (crew won).

We all had 1.3.1 installed and were playing on Windows.

**Comment by Zosh8818** [comment]
Are you sure you voted the imposter the first time? And it's not the other guy that pinged out?

**Comment by dketterer** [comment]
I am pretty sure. We were all in an voice chat and I don't think someone lied.

I thought that the person who pinged out triggered some reevaluation of the game state which in turn ended the game.

**Comment by NotHunter101** [comment]
This is possibly a bug, but it might be more likely that the person who left was actually the Impostor. Assuming this is an actual bug, it has never been reported before. Based on the frequency of Officer kills, it must be incredibly rare, too. I will look into this a little bit when I continue the current re-write, but for now, I'm going to assume this was just miscommunication and not an actual bug.
