### ISSUE TITLE
Roles not random

### ISSUE THREAD

**Issue by w1n4p2nc00k3** [NotHunter101/ExtraRolesAmongUs#39]
When playing in a 10 people lobby, the roles arent really random. We played 3 days for 3 hours per day, and I only was Crewmate or Imposter every single time while my friends e.g. always became Officer. So, specific roles where exclusive for specific people...

**Comment by ismywb** [comment]
That's random. Preventing someone from getting the same role over and over would be literally not random. What you are looking for is a different type of random.

**Comment by NotHunter101** [comment]
^^^ This. Although, if what you're saying is true, that is very unusual. Are you sure the mod is actually installed? If it isn't loaded, you can still play with people who have the mod, but you won't get any special roles (This could be what's happening).

**Comment by w1n4p2nc00k3** [comment]
Well we all installed the mod correctly(everyone can see the additional information on the top left in the main menu), and I dont call it random when in 9 hours of playing, specific players only can be specific roles, because that is what happened. For me i only got Crewmate or Imposter, while my 1st friend only was medic or crewmate, a 2nd friend everytime only was officer or crewmate and a 3rd friend never was crewmate but everytime joker/engineer.

**Comment by benniii1337** [comment]
First 2 days i played that mod with my lobby i never became an extra role, but the host was always one, we thought that there is smth wrong, but in the end it's just random. The 3rd day i actually got several extra roles ^^

![](https://www.americanscientist.org/sites/americanscientist.org/files/20144141249210337-2014-05TechnologueFp170.jpg)

**Comment by ismywb** [comment]
It sounds like that was random @w1n4p2nc00k3 . 

You just didn't get extra roles. You're friends kept getting them, and different ones. That sounds like random to me. 

In order for there to be a problem you would actually need to be reporting that certain players only get certain roles. From a programming standpoint that is *very* specific coding. 

As an example of the kind of random it seems you want, think of a movie theater. A lot of them have their seats in random repeating patterns. But notice how you never see the same pattern 4 seats in a row? That's biased random, and not true random.

**Comment by w1n4p2nc00k3** [comment]
well, i now tested with, 5% Sigma, according to the result the hypothesis p=20% for imposter, p=40% for crewmate and p=10% for each other roles isnt true (n=50). But maybe i just am very unlucky... Thanks for help anyway!
