### ISSUE TITLE
It doesn't work?

### ISSUE THREAD

**Issue by CrabHead** [NotHunter101/ExtraRolesAmongUs#4]
So i'm currently trying to launch among us with the mod but i can't... it loads some cmd thing 

 normal among us launches... any help?
 screen from the cmd ![error](https://user-images.githubusercontent.com/60571885/107042881-86558500-67c2-11eb-9530-67ab9a96fcb3.png)

**Comment by CrabHead** [comment]
i cant extend it for some reason

**Comment by NotHunter101** [comment]
I haven't seen that before. Could you try to reinstall Among Us and re drag all the mod files into the new installation? If you reinstall, make sure you actually go into the Among Us folder and delete all the files, instead of just uninstalling it through steam.

**Comment by NotHunter101** [comment]
Issue resolved in Discord...
