### ISSUE TITLE
Officer Vs Medic

### ISSUE THREAD

**Issue by MQadehar** [NotHunter101/ExtraRolesAmongUs#43]
When the officer tries to kill an impostor who is shielded by the medic, the officer dies. Is this intended ? I would rather expect nothing to happen, but i don't see why the officer dies there.

**Comment by MQadehar** [comment]
Ok, my bad, should have checked the closed issues before. Could this be a toggle option ?

**Comment by NotHunter101** [comment]
It will be a setting in a future update.
