### ISSUE TITLE
Let Sheriff survive against shielded Players

### ISSUE THREAD

**Issue by manniL** [NotHunter101/ExtraRolesAmongUs#47]
Hey 👋 

Right now, the sheriff suicides against shielded players - also Impostors (or the Joker).
IMO it'd be cool to toggle that behavior and allow the Sheriff to survive against the shielded player.
This would mean that the Sheriff knows the shielded player *but* not their role and would make the role more "sustainable".

I'd be happy to implement the settings if the idea will be accepted.

**Comment by NotHunter101** [comment]
Feel free to make a pr that adds these options! If it works, I will merge it.
