### ISSUE TITLE
Murder Attempt ting sound does not appear

### ISSUE THREAD

**Issue by 1jp2003** [NotHunter101/ExtraRolesAmongUs#5]
When I was testing out this mod I had the Murder Attempt Indicator checked yet did not sound when I tried to kill the shielded player. Why does this happen?

**Comment by NotHunter101** [comment]
Yes, I am aware it isn't working. It will most likely be fixed in the next content update or a subsequent patch.

**Comment by NotHunter101** [comment]
Alright, I'm going to assume this issue is resolved. When I update the mod to fix the sounds, I will add a comment here.

**Comment by TallyHoo920** [comment]
@NotHunter101: This is still a recurring issue as no sound is played when there is an attempt to kill a shielded player. Any ideas when the next patch/update will be released?
