### ISSUE TITLE
Suggestion: Implement custom buttons via Reactor-Essentials

### ISSUE THREAD

**Issue by manniL** [NotHunter101/ExtraRolesAmongUs#51]
I've just seen that Reactor-Essentials has a ["template" for CooldownButtons](https://github.com/DorCoMaNdO/Reactor-Essentials/blob/master/Essentials/UI/CooldownButton.cs). This could be useful to decouple the code further.

**Comment by NotHunter101** [comment]
That is definitely something I will look into. When I first started the mod I wasn't even using Reactor, so a lot of faster or better ways to do certain things are still unused.

**Comment by DorCoMaNdO** [comment]
CooldownButton in Essentials will be heavily reworked soon™ so I do not recommend depending on it just yet.
I'm working on version 0.2.0 with (hopefully) support for custom roles, custom player colors and at least some of the rework for CooldownButton.
In the meantime I do recommend updating to Essentials 0.1.3 to update the namespace for custom options as it has changed, as well as ceasing to use any obsolete types as those will be removed in 0.2.0. Note that version 0.1.1 and higher require Reactor CI 39 or higher.

**Comment by DorCoMaNdO** [comment]
First refactor pass of CooldownButton is now available with version [0.2.0-dev.1](https://github.com/DorCoMaNdO/Reactor-Essentials/releases/tag/0.2.0-dev.1).

**Comment by Popeye4242** [comment]
@DorCoMaNdO I have noticed that there is an issue with the `CooldownButton`. When you place the button over the original Kill Button then the button gets slowly pushed out of screen.

**Comment by DorCoMaNdO** [comment]
Could you provide a snippet?

**Comment by Popeye4242** [comment]
```
            var pos = HudManager.KillButton.transform.position;
            OfficerKillButton= new CooldownButton(HudManager.KillButton.renderer.sprite, new Vector2(pos.x, pos.y), 30f, 0f, 10f);
```

**Comment by DorCoMaNdO** [comment]
Try `LocalPosition` instead, I also recommend using `Instantiate` on the sprite because if the button is ever disposed, it will affect the normal kill button (or vice versa if the original button is gone and so is it's sprite), I'll make the button automatically instantiate the sprite with dev.4.

**Comment by DorCoMaNdO** [comment]
Correction, use `localPosition.x * 2 - 1.3F` for x, 0F for Y

**Comment by Popeye4242** [comment]
![yenuLBclBP](https://user-images.githubusercontent.com/35311793/111677003-0db10200-881f-11eb-8257-5ec211c2f3d6.gif)

I have noticed that the buttons position gets modified more than once. I have not used your code but still I think that the button shouldn't jump around and recalculate its position every frame.

```
            x = pos1.x + 1.3f;
            System.Console.WriteLine(x);
                

            OfficerKillButton = new CooldownButton(sprite, new Vector2(x, 0f), Main.Config.OfficerCD, 0f, 10f);
            OfficerKillButton.OnClick += OfficerKillButton_OnClick;
```

**Comment by Popeye4242** [comment]
https://user-images.githubusercontent.com/35311793/111677611-ad6e9000-881f-11eb-914d-b9bebdf67723.mp4

**Comment by Popeye4242** [comment]
I have pushed my code to git for you: https://github.com/Popeye4242/ExtraRolesAmongUs/blob/feature/3.5s/EssentialsCooldownButton/ExtraRoles/Roles/Officer/HudUpdatePatch.cs

**Comment by DorCoMaNdO** [comment]
I have a working fix I'll post as dev.4 in a few hours. Another thing I forgot to mention - don't create the buttons in `HudManager.Start` or `HudManager.Update`, create it in `Plugin.Load()`, everything regarding button handling is done for you, you just need to create it once, unless you dispose it, you should always be able to count on the button existing when you use it's events.
I'll also make the PositionOffset property settable so you could update the position if you need to.

**Comment by Popeye4242** [comment]
I cannot create it in Plugin.Load because the KillButton does not exist at that time where I read my position from.

**Comment by DorCoMaNdO** [comment]
You only need it for the sprite as you can assign the position to the vector I posted in the previous comment. I'll add an option to create a button with the default sprite by passing null.

**Comment by DorCoMaNdO** [comment]
Update dev.4 is now up, pass null to the constructor to keep the kill button sprite, you may receive an error regarding ambiguous call, use `sprite: null` to address it.

**Comment by TheAlexLichter** [comment]
Stale
