### ISSUE TITLE
How do you uninstall/deactivate the mod?

### ISSUE THREAD

**Issue by Korotaxx** [NotHunter101/ExtraRolesAmongUs#56]
I often play your mod with friends and it is a lot of fun, but when i want play in public lobbies or with friends that play Among Us on a phone i cant do it because of the mod. 
Is there any way to revert Among Us to the unmodded version of the game? I couldn't find a tutorial online on how to deactivate or uninstall the mod so far. Can someone tell me how to?

**Comment by NotHunter101** [comment]
Rename the BepInEx folder inside the Among Us directory to anything else,
