### ISSUE TITLE
I can't use the mod. Error on the console.

### ISSUE THREAD

**Issue by Casder58186** [NotHunter101/ExtraRolesAmongUs#58]
When I try to open the game with 4 roles mod, this error appears:

[Error  :   BepInEx] Error loading [Reactor 0.3.0-ci.38] : Exception has been thrown by the target of an invocation.

Then those two:

[Warning:   BepInEx] Skipping [Essentials 0.1.0] because it has a dependency that was not loaded. See previous errors for details.
[Warning:   BepInEx] Skipping [ExtraRoles 1.3.1] because it has a dependency that was not loaded. See previous errors for details.

In the end a classic version of Among Us opens.
What does it mean? What could I do to fix this?

**Comment by Haamiah38** [comment]
I have the same problem

**Comment by KimAndreLippold** [comment]
same here

**Comment by dosentaste** [comment]
same here as well

**Comment by Fabr3tti** [comment]
I had the same problem. Then, i download the Among Us v2020.12.9s and it worked (that was the version the guy on the tutorial was using). Hope i helped u guys :D

**Comment by dosentaste** [comment]
how can i get an older Among us Version?

**Comment by Casder58186** [comment]
Try this link:
https://steamunlocked.pro/among-us-free-download/

**Comment by NotHunter101** [comment]
Multiple people have posted links to pirated versions of the game in this thread, so they have been removed. I can only assume this happens because of an incorrect/pirated Among Us version, and I do not provide issue support for people who don't have legitimate copies of the game.
