### ISSUE TITLE
Soft-Ban for venting as Engineer.

### ISSUE THREAD

**Issue by MaoamDEV** [NotHunter101/ExtraRolesAmongUs#6]
This can be reproduced infinitely. 

Server: aeonlucid/impostor:nightly v1.2.2
https://github.com/Impostor/Impostor

**Comment by NotHunter101** [comment]
Unfortunately, there is an anti-cheat in the Impostor server that does a check that you're an Impostor when you vent. You are able to manually turn this off inside the code, but otherwise, you're probably out of luck playing on Impostor servers.

**Comment by ballaual** [comment]
someone found the code part to edit it?

**Comment by MaoamDEV** [comment]
Currently there is no way to disable the anticheat completely. Only to change the punishment from banning to kicking. 

As long as no PR is being accepted the current workaround is to either disable the Engineer or play on InnerSloth Servers.

**Comment by Phoenix616** [comment]
You might want to mention that in the readme then, currently it claims the Impostor server is compatible.

Also the Impostor developers seem to not be inclined to provide to disable the anti cheat so maybe a mod-side solution would be preferred.

**Comment by Zosh8818** [comment]
Yes, because the Engineer is kind of useless right now...
