### ISSUE TITLE
Compatibility with BetterCrewLink

### ISSUE THREAD

**Issue by BenjaFriend** [NotHunter101/ExtraRolesAmongUs#63]
It would be awesome if this mod was compatible with [Better Crew Link](https://github.com/OhMyGuus/BetterCrewLink) !

**Comment by manniL** [comment]
What do you mean with "compatible"?

AFAIK the mod works fine with the standard crewlink so it should work with Better Crew Link as well, right?

**Comment by NotHunter101** [comment]
As far as I can tell, the mod actually **is** compatible with BetterCrewlink. If I am incorrect, I'd appreciate it if you'd submit another issue with an included description of what actually is not working.
