### ISSUE TITLE
Please Help: Extra Roles Mod error [you disconnected from the server reliable packet 1 (size=102) was not ack'd after 7531ms (9 resends)]

### ISSUE THREAD

**Issue by ItsDeion** [NotHunter101/ExtraRolesAmongUs#64]
**you disconnected from the server 
reliable packet 1 (size=102) was not ack'd after 7531ms (9 resends)**

I'm not sure why this is happening. When I first used the extra roles mod, it was working fully. The mod loaded in the corner of the main menu, and the mod worked in-game with my friends. However, when I tried to play again another day, this error code has continued to keep coming up. I don't know where this is coming from, especially since it was working earlier and now isn't. It has been like this for the past week.

I have tried:

- Restarting my device
- Reconnecting and fully resetting my wifi
- Re-downloading the mod and the process to get it

I would appreciate if anyone would help as soon as possible. I want to play with my friends tomorrow with this mod however it still is not working for me. Thank you for your time.

**Comment by NotHunter101** [comment]
What region are you using?

**Comment by ItsDeion** [comment]
@NotHunter101 
Custom

**Comment by NotHunter101** [comment]
There is no default Custom server. You either have to use NA, Europe, or Asia. If you want to use a custom server, you have to create one yourself.

**Comment by ItsDeion** [comment]
@NotHunter101 

I feel like an idiot, thank you.
