### ISSUE TITLE
Visual Murder Attempt Indicator For Shielded Player

### ISSUE THREAD

**Issue by qzole** [NotHunter101/ExtraRolesAmongUs#65]
Some of us in our group play without sound on our laptops because we are next to each other and hearing what the other is currently doing / what is happening at their location gives away too much info.

It would be nice if the murder attempt indicator would have a visual part. (the shield flashing and quickly scaling up?)

Slightly unrelated, but it would be also nice to have an option for the impostor to have a clear feedback when he tries to kill a shielded player. Without that it takes several seconds to realize that it's not a technical issue that the kill button doesn't do anything .

Awesome mod btw, it really spiced up the game!

**Comment by NotHunter101** [comment]
This will be added in a future version.
