### ISSUE TITLE
Medic Joker Shield Bug

### ISSUE THREAD

**Issue by DonKiiimo** [NotHunter101/ExtraRolesAmongUs#72]
When the medic shields the Joker, we encountered a self kill from the Officer (while Officer kills Joker was turned on). As Impostor you are not able to press the kill button on a shielded Crewmate, whilst as Officer we were able to Press the button on the Joker and ended up with a dead Officer. We didnt notice a Notification when someone tried to kill a shielded Crewmate aswell.

**Comment by Popeye4242** [comment]
Hi, this is intended. The officer should die when attacking a shielded player no matter what role the player is.

**Comment by manniL** [comment]
See https://github.com/NotHunter101/ExtraRolesAmongUs/issues/47 as suggestion.

**Comment by NotHunter101** [comment]
See comment above from Popeye4242.
