### ISSUE TITLE
"Defeat" screen with no winners shown when the Joker leaves right after winning

### ISSUE THREAD

**Issue by jefforion** [NotHunter101/ExtraRolesAmongUs#77]
The Medic won, yet we had to vote the Joker.
But for that to happen, the Joker had to leave the game.

![image](https://user-images.githubusercontent.com/525661/110044749-f582b280-7d49-11eb-8244-e9a934298893.png)

**Comment by NotHunter101** [comment]
This is a known bug that will be fixed in a future patch.
