### ISSUE TITLE
Incompatible with current version v2021.2.21

### ISSUE THREAD

**Issue by FUKU-00** [NotHunter101/ExtraRolesAmongUs#78]
[Info   :   BepInEx] System platform: Bits64, Windows
[Info   : Preloader] Running under Unity v2019.4.9.5308042
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:   BepInEx] Chainloader initialized
[Info   :Unhollower] Registered mono type UnhollowerRuntimeLib.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 3 plugins to load
[Info   :   BepInEx] Loading [Reactor 0.3.0-ci.38]
[Error  :   BepInEx] Error loading [Reactor 0.3.0-ci.38] : Exception has been thrown by the target of an invocation.
[Warning:   BepInEx] Skipping [Essentials 0.1.0] because it has a dependency that was not loaded. See previous errors for details.
[Warning:   BepInEx] Skipping [ExtraRoles 1.3.1] because it has a dependency that was not loaded. See previous errors for details.
[Message:   BepInEx] Chainloader startup complete

**Comment by ItsL3w1s** [comment]
Reactor needs to update

**Comment by TJHeinzo** [comment]
I downloaded the older version of the game [here ](https://nexusgames.to/game/among-us-free-download/)and it worked until the mods get patched

**Comment by NotHunter101** [comment]
The mod is incompatible with the latest version, and will not be updated until Reactor updates.

**Comment by tartsharpcobra** [comment]
I WANT IT TO WOOOOOOOORK

**Comment by lloydnoah** [comment]
?

**Comment by lloydnoah** [comment]
Wait is it for phone

**Comment by piu130** [comment]
@NotHunter101 you should reopen this issue and pin it to reduce duplicates and to make it easy for us to track the status.
