### ISSUE TITLE
Officer can kill an imposter that's in the vent

### ISSUE THREAD

**Issue by sae3023** [NotHunter101/ExtraRolesAmongUs#8]
Steps to reproduce:

1) Have an imposter vent.
2) Have an officer press the "kill" button while standing on that vent.

**Comment by NotHunter101** [comment]
Yes, people can kill others that are in a vent. Similar to how the Engineer can die to an Impostor while inside of the vent, this is an intended feature that balances the Engineer, however weird it may look or play.
