### ISSUE TITLE
Mods not loading when using a VM on Mac

### ISSUE THREAD

**Issue by allisonkoh** [NotHunter101/ExtraRolesAmongUs#89]
The mods are not loaded up in the top left when loading the Among Us game. I am using a VM (Parallels) on Mac.

**Comment by NotHunter101** [comment]
Have you installed the C++ redist in your VM? https://aka.ms/vs/16/release/vc_redist.x86.exe

**Comment by allisonkoh** [comment]
I have not- will try it out. Thanks!
