### ISSUE TITLE
Officer Cooldown Not Reset After Meetings - Non-host

### ISSUE THREAD

**Issue by basarama** [NotHunter101/ExtraRolesAmongUs#9]
After meetings it appears Officer kill cooldown resets only if the Officer is the host of the lobby, otherwise they can kill immediately. I'm not sure if it's intended to reset (I think it should personally) but it's not consistent between players is the main issue I believe.

**Comment by NotHunter101** [comment]
It's working for me when I test it locally with 4 separate clients. It is very likely that the person whose cooldown is not updating is running an older patch. Make sure your whole lobby has the latest version from here: https://github.com/NotHunter101/ExtraRolesAmongUs/releases/tag/v1.2.4

**Comment by basarama** [comment]
Thanks for the quick reply, definitely my fault for not realizing how fast you're putting out updates! I only checked this wasn't a previously issue repot 😓
